# Generated by Django 5.2.5 on 2025-10-27 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('content_type', models.CharField(choices=[('programme', 'Programme'), ('echeance', 'Échéance'), ('difficulte', 'Difficulté'), ('ressource', 'Ressource'), ('annonce', 'Annonce')], default='programme', max_length=20, verbose_name='Type de contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('deadline', models.DateTimeField(blank=True, help_text='Pour les échéances uniquement', null=True, verbose_name='Date limite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Élément du Feed',
                'verbose_name_plural': 'Éléments du Feed',
                'ordering': ['-created_at'],
            },
        ),
    ]
