# Generated by Django 5.2.7 on 2025-10-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/')),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'Vidéo'), ('IMAGE', 'Image')], max_length=10)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True)),
                ('formulas', models.TextField(blank=True)),
                ('images_extracted', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
