# Generated by Django 5.2.7 on 2025-10-27 14:53

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/'),

        ),
    ]
