# Generated by Django 5.2.7 on 2025-10-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_processed_alter_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
