# Generated by Django 5.2.7 on 2025-10-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/'),
        ),
    ]
