# Generated by Django 5.2.5 on 2025-10-29 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
